FROM pytorch/pytorch:1.8.1-cuda11.1-cudnn8-devel
FROM deepspeed/deepspeed:latest-torch170-cuda110
RUN apt update -y && apt install g++ -y
ADD ./requirements.txt /requirements.txt
ADD ./v1 /v1
RUN pip install -f https://download.pytorch.org/whl/torch_stable.html -r /requirements.txt
